# Generated by Django 4.2.4 on 2023-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neon_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
