# Generated by Django 4.2.4 on 2023-08-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("neon_api", "0002_alter_salary_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="user",
            new_name="cpf",
        ),
    ]
