# Generated by Django 4.2.4 on 2023-08-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("neon_api", "0003_rename_user_salary_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="cpf",
            new_name="user",
        ),
    ]
